### PR TITLE
Flexible icon

### PR DESCRIPTION
**Pull request by oscarshaitan**
I leave the icon as Widget so the user can use _**ImageIcon**_ as he place to add any icon 
```
Center(
     child: ImageIcon(
        AssetImage('assets/images/w_icon.png'),
        color: Colors.white,
        size: 32,
    ),
)
```
the result:
image

### CODE REVIEW

**Comment by oscarshaitan** [comment]
sound nice give me some days I will upload an update

**Comment by oscarshaitan** [comment]
@Friiiis  ready please review, the example I leavit to you pal :) sorry for the long time :D

**Comment by jonatascm** [comment]
@Friiiis, hello! 
Any news on that PR?
I could help to maintain this lib as well! :)

**Comment by oscarshaitan** [comment]
I decide to fork the code and put it into the project :(

**Comment by Friiiis** [comment]
Hello guys, and sorry for never returning back. As you've probably guessed, I do not have time to regularly maintain the repo, which I apologize. I just returned form vacation, so I will look into the two PRs in the following week.

**Pull request merged**
